// Definição centralizada de todos os menus disponíveis no sistema
// Este arquivo é usado para sincronizar os menus do Layout.tsx com as permissões do GruposAcessoCRUD

export const MENU_CONFIG = [
  { id: "Dashboards", label: "Dashboards" },
  { id: "Dashboard", label: "Painel" },
  { id: "Clientes", label: "Leads" },
  { id: "Atendimento", label: "Chats" },
  { id: "Painel Chats", label: "Painel" },
  { id: "Dashboard Atendente", label: "Dashboard Atendente" },
  { id: "Dashboard Supervisor", label: "Dashboard Supervisor" },
  { id: "SLA Dashboard", label: "Dashboard SLA" },
  { id: "Analytics Dashboard", label: "Analytics Avançado" },
  { id: "Dashboard CSAT/NPS", label: "Pesquisas de Satisfação" },
  { id: "Dashboard Gastos IA", label: "Gastos com IA" },
  { id: "CSAT/NPS", label: "Pesquisas de Satisfação (Config)" },
  { id: "Base de Conhecimento", label: "Base de Conhecimento" },
  { id: "Quality Assurance", label: "Quality Assurance" },
  { id: "Campanhas", label: "Calendário" },
  { id: "Vendas", label: "Vendas" },
  { id: "Orçamento", label: "Orçamento" },
  { id: "Config Vendas", label: "Configuração de Vendas" },
  { id: "Importação Produtos Sub", label: "Importação de Produtos de Terceiro" },
  { id: "Conteúdos", label: "Listas" },
  { id: "Contatos", label: "Contatos" },
  { id: "Empresas", label: "Empresas" },
  { id: "Todos", label: "Todos" },
  { id: "Vínculos Empresas", label: "Vínculo Empresas X Usuário / Segmento" },
  { id: "Vínculos Contatos", label: "Vínculo Contatos X Usuário / Segmento" },
  { id: "Email", label: "E-mail" },
  { id: "Caixa de Entrada", label: "Caixa de Entrada" },
  { id: "Enviados", label: "Enviados" },
  { id: "Arquivados", label: "Arquivados" },
  { id: "Lixeira", label: "Lixeira" },
  { id: "Bot Test", label: "Bot" },
  { id: "Criar Bot", label: "Criar / Editar Bot" },
  { id: "Testar", label: "Testar Bot" },
  { id: "Desenho", label: "Marketing" },
  { id: "Canvas", label: "Canvas" },
  { id: "Automações", label: "Automações" },
  { id: "Campanhas Marketing", label: "Campanhas" },
  { id: "Relatórios", label: "Relatórios" },
  { id: "Meus Conjuntos", label: "Meus Conjuntos de Itens" },
  { id: "Telefonia", label: "Telefonia" },
  { id: "Softphone", label: "Softphone" },
  { id: "Videochamada", label: "Videochamada" },
  { id: "Minha Conta", label: "Minha Conta" },
  { id: "Perfil", label: "Perfil" },
  { id: "Alterar Senha", label: "Alterar Senha" },
  { id: "Configurações", label: "Configurações" },
  { id: "Config Filas", label: "Filas de Atendimento" },
  { id: "Config Skills", label: "Skills de Atendimento" },
  { id: "Monitor de Filas", label: "Monitor de Filas" },
  { id: "Omnichannel Builder", label: "Workflow Builder Omnichannel" },
  { id: "Teste de Webhooks", label: "Teste de Webhooks" },
  { id: "Variáveis Globais", label: "Variáveis Globais" },
  { id: "Teste Campanhas", label: "Teste Campanhas" },
  { id: "Gerenciar Atalhos", label: "Gerenciar Atalhos" },
  { id: "SLA Config", label: "SLA" },
  { id: "Análise de Sentimento", label: "Análise de Sentimento" },
  { id: "Automação de Vendas", label: "Regras para o Orçamento" },
  { id: "Editor de Regras", label: "Editor de Regras" },
  { id: "Base de Conhecimento", label: "Base de Conhecimento" },
  { id: "Logística", label: "Logística" },
  { id: "Logística Dashboard", label: "Dashboard Logística" },
  { id: "Logística Veículos", label: "Veículos" },
  { id: "Logística Histórico", label: "Histórico" },
  { id: "Logística Roteirização", label: "Roteirização" },
  { id: "Logística Rotas", label: "Rotas Salvas" },
  { id: "Logística Automações", label: "Automações" },
  { id: "Logística Config", label: "Configuração" },
  { id: "Logística Monitoramento", label: "Monitoramento" },
  { id: "Marketplaces", label: "Marketplaces" },
  { id: "Marketplace Hub", label: "Hub de Marketplaces" },
  { id: "Marketplace Produtos", label: "Produtos x Canais" },
  { id: "Marketplace Pedidos", label: "Pedidos" },
  { id: "Ads", label: "Ads" },
  { id: "Ads Campaigns", label: "Campanhas Ads" },
  { id: "Ads Reports", label: "Relatórios Ads" },
  { id: "Ads Alerts", label: "Alertas Ads" },
  { id: "Ads Dashboard", label: "Dashboard Geral Ads" },
  { id: "Ads Google", label: "Google Ads" },
  { id: "Ads Meta", label: "Meta Ads" },
  { id: "Ads TikTok", label: "TikTok Ads" },
  { id: "Ads MercadoLivre", label: "Mercado Livre Ads" },
  { id: "Ads Amazon", label: "Amazon Ads" },
  { id: "Ads Credentials", label: "Credenciais Ads" },
  { id: "Ads Logs", label: "Logs de Coleta Ads" },
  { id: "Ads Automation", label: "Automações Ads" },
  { id: "Robô de Preços", label: "Robô de Preços" },
] as const;

// Lista apenas dos IDs dos menus (para compatibilidade com código existente)
export const MENUS_DISPONIVEIS = MENU_CONFIG.map(menu => menu.id);
