// Definição centralizada de todos os menus disponíveis no sistema
// Este arquivo é usado para sincronizar os menus do Layout.tsx com as permissões do GruposAcessoCRUD

export const MENU_CONFIG = [
  { id: "Dashboard", label: "Painel" },
  { id: "Clientes", label: "Leads" },
  { id: "Atendimento", label: "Chats" },
  { id: "Painel Chats", label: "Painel" },
  { id: "Dashboard Atendente", label: "Dashboard Atendente" },
  { id: "Dashboard Supervisor", label: "Dashboard Supervisor" },
  { id: "Campanhas", label: "Calendário" },
  { id: "Orçamentos", label: "Orçamentos" },
  { id: "Conteúdos", label: "Listas" },
  { id: "Contatos", label: "Contatos" },
  { id: "Empresas", label: "Empresas" },
  { id: "Todos", label: "Todos" },
  { id: "Vínculos Empresas", label: "Vínculo Empresas X Usuário / Segmento" },
  { id: "Vínculos Contatos", label: "Vínculo Contatos X Usuário / Segmento" },
  { id: "Email", label: "E-mail" },
  { id: "Caixa de Entrada", label: "Caixa de Entrada" },
  { id: "Enviados", label: "Enviados" },
  { id: "Arquivados", label: "Arquivados" },
  { id: "Lixeira", label: "Lixeira" },
  { id: "Bot Test", label: "Bot" },
  { id: "Criar Bot", label: "Criar / Editar Bot" },
  { id: "Testar", label: "Testar Bot" },
  { id: "Desenho", label: "Marketing" },
  { id: "Canvas", label: "Canvas" },
  { id: "Automações", label: "Automações" },
  { id: "Campanhas Marketing", label: "Campanhas" },
  { id: "Relatórios", label: "Relatórios" },
  { id: "Importação Produtos", label: "Importação de Produtos de Terceiro" },
  { id: "Telefonia", label: "Telefonia" },
  { id: "Softphone", label: "Softphone" },
  { id: "Videochamada", label: "Videochamada" },
  { id: "Minha Conta", label: "Minha Conta" },
  { id: "Perfil", label: "Perfil" },
  { id: "Alterar Senha", label: "Alterar Senha" },
  { id: "Configurações", label: "Configurações" },
  { id: "Config Geral", label: "Configurações Gerais" },
  { id: "Config Skills", label: "Skills de Atendimento" },
  { id: "Monitor de Filas", label: "Monitor de Filas" },
  { id: "Omnichannel Builder", label: "Workflow Builder Omnichannel" },
  { id: "Teste de Webhooks", label: "Teste de Webhooks" },
  { id: "Variáveis Globais", label: "Variáveis Globais" },
  { id: "Teste Campanhas", label: "Teste Campanhas" },
  { id: "Gerenciar Atalhos", label: "Gerenciar Atalhos" },
] as const;

// Lista apenas dos IDs dos menus (para compatibilidade com código existente)
export const MENUS_DISPONIVEIS = MENU_CONFIG.map(menu => menu.id);
