project_id = "ioxugupvxlcdweldocmq"

[functions.execute-dynamic-query]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.fetch-emails]
verify_jwt = true

[functions.extract-orcamento-items]
verify_jwt = false

[functions.suggest-products]
verify_jwt = false


[functions.whatsapp-webhook]
verify_jwt = false

[functions.webhook-entrada]
verify_jwt = false

[functions.test-report-query]
verify_jwt = false

[functions.reportbro-preview]
verify_jwt = false

[functions.gerar-relatorio-pdf]
verify_jwt = false

[functions.consultar-cnpj]
verify_jwt = false

