project_id = "ioxugupvxlcdweldocmq"

[functions.execute-dynamic-query]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.fetch-emails]
verify_jwt = true

[functions.extract-orcamento-items]
verify_jwt = false

[functions.suggest-products]
verify_jwt = false
