// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna dados do usu\xE1rio Pilar autenticado (id, nome, e-mail, estabelecimento).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("usuarios").select("id, nome, email, estabelecimento_id").eq("auth_user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { auth_user_id: ctx.getUserId(), email: ctx.getUserEmail() }) }],
      structuredContent: { user: data }
    };
  }
});

// src/lib/mcp/tools/list-empresas.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_empresas_default = defineTool2({
  name: "list_empresas",
  title: "Listar empresas (com filtros)",
  description: "Lista empresas do CRM Pilar vis\xEDveis para o usu\xE1rio autenticado. Permite filtrar por UF (estado), cidade, segmento (por id ou nome), e exigir presen\xE7a de e-mail e/ou WhatsApp. Retorna nome, nome fantasia, CNPJ, e-mail(s), telefone, WhatsApp(s), cidade, UF e segmento \u2014 pronto para o assistente montar tabela.",
  inputSchema: {
    search: z.string().optional().describe("Texto livre em nome, nome fantasia ou CNPJ."),
    uf: z.string().length(2).optional().describe("UF (2 letras), ex: SP, RJ, MG."),
    cidade: z.string().optional().describe("Cidade (busca parcial, case-insensitive)."),
    segmento_id: z.string().uuid().optional().describe("ID do segmento (use list_segmentos para descobrir)."),
    segmento_nome: z.string().optional().describe("Nome do segmento (busca parcial). Alternativa a segmento_id."),
    com_email: z.boolean().optional().describe("Se true, retorna somente empresas com e-mail cadastrado."),
    com_whatsapp: z.boolean().optional().describe("Se true, retorna somente empresas com WhatsApp/telefone cadastrado."),
    limit: z.number().int().positive().max(500).optional().describe("M\xE1ximo de registros (padr\xE3o 50, m\xE1x 500).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, uf, cidade, segmento_id, segmento_nome, com_email, com_whatsapp, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let segIds = null;
    if (segmento_id) {
      segIds = [segmento_id];
    } else if (segmento_nome && segmento_nome.trim()) {
      const { data: segs, error: segErr } = await sb.from("segmentos").select("id, nome").ilike("nome", `%${segmento_nome.trim()}%`);
      if (segErr) return { content: [{ type: "text", text: segErr.message }], isError: true };
      if (!segs || segs.length === 0) {
        return {
          content: [{ type: "text", text: `Nenhum segmento encontrado com nome "${segmento_nome}".` }],
          structuredContent: { empresas: [], count: 0 }
        };
      }
      segIds = segs.map((s) => s.id);
    }
    let q = sb.from("empresas").select(
      "id, nome, nome_fantasia, cnpj, email, emails_vinculados, telefone, whatsapps_vinculados, cidade, estado, segmento_id, segmentos(nome)"
    ).order("nome").limit(limit ?? 50);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`nome.ilike.${s},nome_fantasia.ilike.${s},cnpj.ilike.${s}`);
    }
    if (uf) q = q.ilike("estado", uf.trim());
    if (cidade && cidade.trim()) q = q.ilike("cidade", `%${cidade.trim()}%`);
    if (segIds) q = q.in("segmento_id", segIds);
    if (com_email) q = q.not("email", "is", null).neq("email", "");
    if (com_whatsapp) q = q.not("telefone", "is", null).neq("telefone", "");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      id: r.id,
      nome: r.nome,
      nome_fantasia: r.nome_fantasia,
      cnpj: r.cnpj,
      email: r.email,
      emails_extras: r.emails_vinculados ?? [],
      whatsapp: r.telefone,
      whatsapps_extras: r.whatsapps_vinculados ?? [],
      cidade: r.cidade,
      uf: r.estado,
      segmento: r.segmentos?.nome ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { empresas: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/list-produtos.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_produtos_default = defineTool3({
  name: "list_produtos",
  title: "Listar produtos",
  description: "Lista produtos do estabelecimento do usu\xE1rio autenticado. Suporta busca por nome/c\xF3digo.",
  inputSchema: {
    search: z2.string().optional().describe("Texto a buscar em nome, c\xF3digo ou marca."),
    limit: z2.number().int().positive().max(100).optional().describe("N\xFAmero m\xE1ximo (padr\xE3o 25, m\xE1x 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("produtos").select("id, nome, codigo, marca, estoque, preco_tabela, preco_minimo, ativo").order("nome").limit(limit ?? 25);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`nome.ilike.${s},codigo.ilike.${s},marca.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { produtos: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ioxugupvxlcdweldocmq";
var mcp_default = defineMcp({
  name: "pilar-mcp",
  title: "Pilar CRM MCP",
  version: "0.1.0",
  instructions: "Ferramentas do Pilar CRM. Use `whoami` para verificar o usu\xE1rio autenticado, `list_empresas` para consultar empresas/clientes cadastrados e `list_produtos` para consultar o cat\xE1logo de produtos. Todas respeitam as permiss\xF5es do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_empresas_default, list_produtos_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
