// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna dados do usu\xE1rio Pilar autenticado (id, nome, e-mail, estabelecimento).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("usuarios").select("id, nome, email, estabelecimento_id").eq("auth_user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { auth_user_id: ctx.getUserId(), email: ctx.getUserEmail() }) }],
      structuredContent: { user: data }
    };
  }
});

// src/lib/mcp/tools/list-empresas.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_empresas_default = defineTool2({
  name: "list_empresas",
  title: "Listar empresas",
  description: "Lista empresas do CRM Pilar vis\xEDveis para o usu\xE1rio autenticado. Suporta busca textual e limite.",
  inputSchema: {
    search: z.string().optional().describe("Texto a buscar em raz\xE3o social, nome fantasia ou CNPJ/CPF."),
    limit: z.number().int().positive().max(100).optional().describe("N\xFAmero m\xE1ximo de registros (padr\xE3o 25, m\xE1x 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("empresas").select("id, razao_social, nome_fantasia, cpf_cnpj, tipo_pessoa, email, telefone, cidade, uf").order("razao_social").limit(limit ?? 25);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`razao_social.ilike.${s},nome_fantasia.ilike.${s},cpf_cnpj.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { empresas: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-produtos.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_produtos_default = defineTool3({
  name: "list_produtos",
  title: "Listar produtos",
  description: "Lista produtos do estabelecimento do usu\xE1rio autenticado. Suporta busca por nome/c\xF3digo.",
  inputSchema: {
    search: z2.string().optional().describe("Texto a buscar em nome, c\xF3digo ou marca."),
    limit: z2.number().int().positive().max(100).optional().describe("N\xFAmero m\xE1ximo (padr\xE3o 25, m\xE1x 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("produtos").select("id, nome, codigo, marca, estoque, preco_tabela, preco_minimo, ativo").order("nome").limit(limit ?? 25);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`nome.ilike.${s},codigo.ilike.${s},marca.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { produtos: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ioxugupvxlcdweldocmq";
var mcp_default = defineMcp({
  name: "pilar-mcp",
  title: "Pilar CRM MCP",
  version: "0.1.0",
  instructions: "Ferramentas do Pilar CRM. Use `whoami` para verificar o usu\xE1rio autenticado, `list_empresas` para consultar empresas/clientes cadastrados e `list_produtos` para consultar o cat\xE1logo de produtos. Todas respeitam as permiss\xF5es do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_empresas_default, list_produtos_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
