// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna dados do usu\xE1rio Pilar autenticado (id, nome, e-mail, estabelecimento).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("usuarios").select("id, nome, email, estabelecimento_id").eq("auth_user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { auth_user_id: ctx.getUserId(), email: ctx.getUserEmail() }) }],
      structuredContent: { user: data }
    };
  }
});

// src/lib/mcp/tools/list-empresas.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_empresas_default = defineTool2({
  name: "list_empresas",
  title: "Listar empresas (com filtros)",
  description: "Lista empresas do CRM Pilar vis\xEDveis para o usu\xE1rio autenticado. Permite filtrar por UF (estado), cidade, segmento (por id ou nome), e exigir presen\xE7a de e-mail e/ou WhatsApp. Retorna nome, nome fantasia, CNPJ, e-mail(s), telefone, WhatsApp(s), cidade, UF e segmento \u2014 pronto para o assistente montar tabela.",
  inputSchema: {
    search: z.string().optional().describe("Texto livre em nome, nome fantasia ou CNPJ."),
    uf: z.string().length(2).optional().describe("UF (2 letras), ex: SP, RJ, MG."),
    cidade: z.string().optional().describe("Cidade (busca parcial, case-insensitive)."),
    segmento_id: z.string().uuid().optional().describe("ID do segmento (use list_segmentos para descobrir)."),
    segmento_nome: z.string().optional().describe("Nome do segmento (busca parcial). Alternativa a segmento_id."),
    com_email: z.boolean().optional().describe("Se true, retorna somente empresas com e-mail cadastrado."),
    com_whatsapp: z.boolean().optional().describe("Se true, retorna somente empresas com WhatsApp/telefone cadastrado."),
    limit: z.number().int().positive().max(500).optional().describe("M\xE1ximo de registros (padr\xE3o 50, m\xE1x 500).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, uf, cidade, segmento_id, segmento_nome, com_email, com_whatsapp, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let segIds = null;
    if (segmento_id) {
      segIds = [segmento_id];
    } else if (segmento_nome && segmento_nome.trim()) {
      const { data: segs, error: segErr } = await sb.from("segmentos").select("id, nome").ilike("nome", `%${segmento_nome.trim()}%`);
      if (segErr) return { content: [{ type: "text", text: segErr.message }], isError: true };
      if (!segs || segs.length === 0) {
        return {
          content: [{ type: "text", text: `Nenhum segmento encontrado com nome "${segmento_nome}".` }],
          structuredContent: { empresas: [], count: 0 }
        };
      }
      segIds = segs.map((s) => s.id);
    }
    let q = sb.from("empresas").select(
      "id, nome, nome_fantasia, cnpj, email, emails_vinculados, telefone, whatsapps_vinculados, cidade, estado, segmento_id, segmentos(nome)"
    ).order("nome").limit(limit ?? 50);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`nome.ilike.${s},nome_fantasia.ilike.${s},cnpj.ilike.${s}`);
    }
    if (uf) q = q.ilike("estado", uf.trim());
    if (cidade && cidade.trim()) q = q.ilike("cidade", `%${cidade.trim()}%`);
    if (segIds) q = q.in("segmento_id", segIds);
    if (com_email) q = q.not("email", "is", null).neq("email", "");
    if (com_whatsapp) q = q.not("telefone", "is", null).neq("telefone", "");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      id: r.id,
      nome: r.nome,
      nome_fantasia: r.nome_fantasia,
      cnpj: r.cnpj,
      email: r.email,
      emails_extras: r.emails_vinculados ?? [],
      whatsapp: r.telefone,
      whatsapps_extras: r.whatsapps_vinculados ?? [],
      cidade: r.cidade,
      uf: r.estado,
      segmento: r.segmentos?.nome ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { empresas: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/list-produtos.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_produtos_default = defineTool3({
  name: "list_produtos",
  title: "Listar produtos",
  description: "Lista produtos do estabelecimento do usu\xE1rio autenticado. Suporta busca por nome/c\xF3digo.",
  inputSchema: {
    search: z2.string().optional().describe("Texto a buscar em nome, c\xF3digo ou marca."),
    limit: z2.number().int().positive().max(100).optional().describe("N\xFAmero m\xE1ximo (padr\xE3o 25, m\xE1x 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("produtos").select("id, nome, codigo, marca, estoque, preco_tabela, preco_minimo, ativo").order("nome").limit(limit ?? 25);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`nome.ilike.${s},codigo.ilike.${s},marca.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { produtos: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-segmentos.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_segmentos_default = defineTool4({
  name: "list_segmentos",
  title: "Listar segmentos",
  description: "Lista os segmentos de empresa cadastrados no Pilar. Use para descobrir o id/nome de um segmento antes de filtrar em list_empresas.",
  inputSchema: {
    search: z3.string().optional().describe("Filtro parcial pelo nome do segmento."),
    limit: z3.number().int().positive().max(200).optional().describe("M\xE1ximo (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("segmentos").select("id, nome").order("nome").limit(limit ?? 100);
    if (search && search.trim()) q = q.ilike("nome", `%${search.trim()}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { segmentos: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/add-prospeccao-empresa.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var EmpresaSchema = z4.object({
  nome: z4.string().min(1).describe("Raz\xE3o social ou nome da empresa (obrigat\xF3rio)."),
  nome_fantasia: z4.string().optional(),
  cnpj: z4.string().optional(),
  email: z4.string().optional(),
  telefone: z4.string().optional().describe("Telefone geral."),
  whatsapp: z4.string().optional().describe("N\xFAmero WhatsApp com DDD."),
  site: z4.string().optional(),
  endereco: z4.string().optional(),
  bairro: z4.string().optional(),
  cidade: z4.string().optional(),
  estado: z4.string().optional().describe("UF (2 letras)."),
  cep: z4.string().optional(),
  cnae_principal: z4.string().optional(),
  cnae_descricao: z4.string().optional(),
  segmento_nome: z4.string().optional().describe("Segmento (texto livre)."),
  descricao: z4.string().optional().describe("Descri\xE7\xE3o / resumo da empresa."),
  redes_sociais: z4.object({
    instagram: z4.string().optional(),
    facebook: z4.string().optional(),
    linkedin: z4.string().optional(),
    youtube: z4.string().optional(),
    tiktok: z4.string().optional()
  }).partial().optional(),
  fontes: z4.array(z4.string().url()).optional().describe("URLs das fontes usadas na pesquisa."),
  // ===== Qualificação / enriquecimento =====
  contato_nome: z4.string().optional().describe("Nome do decisor/contato principal."),
  contato_cargo: z4.string().optional().describe("Cargo do contato (ex.: S\xF3cio, Diretor Comercial)."),
  contato_email: z4.string().optional(),
  contato_telefone: z4.string().optional(),
  porte: z4.string().optional().describe("MEI, ME, EPP, M\xE9dio, Grande."),
  faturamento_estimado: z4.string().optional().describe("Faixa de faturamento anual estimado."),
  funcionarios_estimado: z4.string().optional().describe("Faixa de n\xBA de funcion\xE1rios (ex.: 1-9, 10-49)."),
  data_fundacao: z4.string().optional().describe("Data de funda\xE7\xE3o em YYYY-MM-DD."),
  situacao_cadastral: z4.string().optional().describe("ATIVA, BAIXADA, SUSPENSA, INAPTA."),
  score: z4.number().int().min(0).max(100).optional().describe("Score de qualifica\xE7\xE3o 0-100."),
  score_motivo: z4.string().optional().describe("Justificativa curta do score."),
  produtos_interesse: z4.array(z4.string()).optional().describe("Produtos/servi\xE7os de interesse."),
  prioridade: z4.string().optional().describe("alta, media, baixa."),
  latitude: z4.number().optional(),
  longitude: z4.number().optional(),
  tags: z4.array(z4.string()).optional(),
  observacoes_internas: z4.string().optional(),
  origem: z4.string().optional().describe("Origem do lead. Use 'vendedor' para representantes comerciais, 'claude-code' (default) para empresas."),
  extras: z4.record(z4.any()).optional().describe("Qualquer dado extra relevante em JSON.")
});
var add_prospeccao_empresa_default = defineTool5({
  name: "salvar_empresa_prospectada",
  title: "Salvar empresa prospectada",
  description: "Insere UMA empresa pesquisada na web na tela 'Prospec\xE7\xE3o Empresas' do Listas do Pilar CRM. Use para trazer leads pesquisados de fontes externas (site, Google, LinkedIn, etc.) para dentro do Pilar. Depois o usu\xE1rio revisa e importa para o cadastro definitivo de Empresas. Para v\xE1rios leads de uma vez, use `salvar_empresas_prospectadas`.",
  inputSchema: EmpresaSchema.shape,
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data, error } = await sb.from("prospeccao_empresas").insert({
      user_id: ctx.getUserId(),
      nome: input.nome,
      nome_fantasia: input.nome_fantasia ?? null,
      cnpj: input.cnpj ?? null,
      email: input.email ?? null,
      telefone: input.telefone ?? null,
      whatsapp: input.whatsapp ?? null,
      site: input.site ?? null,
      endereco: input.endereco ?? null,
      bairro: input.bairro ?? null,
      cidade: input.cidade ?? null,
      estado: input.estado ?? null,
      cep: input.cep ?? null,
      cnae_principal: input.cnae_principal ?? null,
      cnae_descricao: input.cnae_descricao ?? null,
      segmento_nome: input.segmento_nome ?? null,
      descricao: input.descricao ?? null,
      redes_sociais: input.redes_sociais ?? {},
      fontes: input.fontes ?? [],
      contato_nome: input.contato_nome ?? null,
      contato_cargo: input.contato_cargo ?? null,
      contato_email: input.contato_email ?? null,
      contato_telefone: input.contato_telefone ?? null,
      porte: input.porte ?? null,
      faturamento_estimado: input.faturamento_estimado ?? null,
      funcionarios_estimado: input.funcionarios_estimado ?? null,
      data_fundacao: input.data_fundacao ?? null,
      situacao_cadastral: input.situacao_cadastral ?? null,
      score: input.score ?? null,
      score_motivo: input.score_motivo ?? null,
      produtos_interesse: input.produtos_interesse ?? [],
      prioridade: input.prioridade ?? null,
      latitude: input.latitude ?? null,
      longitude: input.longitude ?? null,
      tags: input.tags ?? [],
      observacoes_internas: input.observacoes_internas ?? null,
      extras: input.extras ?? {},
      origem: input.origem ?? "claude-code",
      status: "novo"
    }).select("id, nome").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Adicionada: ${data.nome} (id ${data.id})` }],
      structuredContent: { id: data.id, nome: data.nome }
    };
  }
});

// src/lib/mcp/tools/add-prospeccao-empresas-bulk.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var Empresa = z5.object({
  nome: z5.string().min(1),
  nome_fantasia: z5.string().optional(),
  cnpj: z5.string().optional(),
  email: z5.string().optional(),
  telefone: z5.string().optional(),
  whatsapp: z5.string().optional(),
  site: z5.string().optional(),
  endereco: z5.string().optional(),
  bairro: z5.string().optional(),
  cidade: z5.string().optional(),
  estado: z5.string().optional(),
  cep: z5.string().optional(),
  cnae_principal: z5.string().optional(),
  cnae_descricao: z5.string().optional(),
  segmento_nome: z5.string().optional(),
  descricao: z5.string().optional(),
  redes_sociais: z5.record(z5.string()).optional(),
  fontes: z5.array(z5.string()).optional(),
  contato_nome: z5.string().optional(),
  contato_cargo: z5.string().optional(),
  contato_email: z5.string().optional(),
  contato_telefone: z5.string().optional(),
  porte: z5.string().optional(),
  faturamento_estimado: z5.string().optional(),
  funcionarios_estimado: z5.string().optional(),
  data_fundacao: z5.string().optional(),
  situacao_cadastral: z5.string().optional(),
  score: z5.number().int().min(0).max(100).optional(),
  score_motivo: z5.string().optional(),
  produtos_interesse: z5.array(z5.string()).optional(),
  prioridade: z5.string().optional(),
  latitude: z5.number().optional(),
  longitude: z5.number().optional(),
  tags: z5.array(z5.string()).optional(),
  observacoes_internas: z5.string().optional(),
  extras: z5.record(z5.any()).optional()
});
var add_prospeccao_empresas_bulk_default = defineTool6({
  name: "salvar_empresas_prospectadas",
  title: "Salvar v\xE1rias empresas prospectadas",
  description: "Insere um LOTE de empresas pesquisadas na web em 'Prospec\xE7\xE3o Empresas' do Pilar CRM. Use quando o assistente j\xE1 compilou uma lista (ex.: 20 ind\xFAstrias em SP) \u2014 envia todas de uma vez, muito mais r\xE1pido que chamar `salvar_empresa_prospectada` v\xE1rias vezes. M\xE1ximo 100 por chamada.",
  inputSchema: {
    empresas: z5.array(Empresa).min(1).max(100).describe("Lista de empresas a inserir.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ empresas }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser6(ctx);
    const userId = ctx.getUserId();
    const rows = empresas.map((e) => ({
      user_id: userId,
      nome: e.nome,
      nome_fantasia: e.nome_fantasia ?? null,
      cnpj: e.cnpj ?? null,
      email: e.email ?? null,
      telefone: e.telefone ?? null,
      whatsapp: e.whatsapp ?? null,
      site: e.site ?? null,
      endereco: e.endereco ?? null,
      bairro: e.bairro ?? null,
      cidade: e.cidade ?? null,
      estado: e.estado ?? null,
      cep: e.cep ?? null,
      cnae_principal: e.cnae_principal ?? null,
      cnae_descricao: e.cnae_descricao ?? null,
      segmento_nome: e.segmento_nome ?? null,
      descricao: e.descricao ?? null,
      redes_sociais: e.redes_sociais ?? {},
      fontes: e.fontes ?? [],
      contato_nome: e.contato_nome ?? null,
      contato_cargo: e.contato_cargo ?? null,
      contato_email: e.contato_email ?? null,
      contato_telefone: e.contato_telefone ?? null,
      porte: e.porte ?? null,
      faturamento_estimado: e.faturamento_estimado ?? null,
      funcionarios_estimado: e.funcionarios_estimado ?? null,
      data_fundacao: e.data_fundacao ?? null,
      situacao_cadastral: e.situacao_cadastral ?? null,
      score: e.score ?? null,
      score_motivo: e.score_motivo ?? null,
      produtos_interesse: e.produtos_interesse ?? [],
      prioridade: e.prioridade ?? null,
      latitude: e.latitude ?? null,
      longitude: e.longitude ?? null,
      tags: e.tags ?? [],
      observacoes_internas: e.observacoes_internas ?? null,
      extras: e.extras ?? {},
      origem: "claude-code",
      status: "novo"
    }));
    const { data, error } = await sb.from("prospeccao_empresas").insert(rows).select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Inseridas ${data?.length ?? 0} empresas na Prospec\xE7\xE3o.` }],
      structuredContent: { inseridas: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/consultar-tabela.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var consultar_tabela_default = defineTool7({
  name: "consultar_tabela",
  title: "Consultar uma tabela liberada",
  description: "Consulta uma tabela do sistema Pilar que foi previamente liberada pelo administrador na tela 'Disponibilizar dados para Cloud Code / Cursor / ChatGPT'. Use 'listar_tabelas_disponiveis' primeiro para saber quais tabelas est\xE3o dispon\xEDveis. Retorna os registros (respeitando RLS do usu\xE1rio autenticado).",
  inputSchema: {
    tabela: z6.string().describe("Nome exato da tabela (ex.: empresas, produtos, orcamentos). Precisa estar na lista de tabelas liberadas."),
    colunas: z6.string().optional().describe("Colunas separadas por v\xEDrgula (padr\xE3o: *)."),
    limit: z6.number().int().positive().max(500).optional().describe("M\xE1ximo de registros (padr\xE3o 50, m\xE1x 500)."),
    order_by: z6.string().optional().describe("Coluna para ordenar."),
    ordem: z6.enum(["asc", "desc"]).optional().describe("Dire\xE7\xE3o da ordena\xE7\xE3o (padr\xE3o asc).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tabela, colunas, limit, order_by, ordem }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser7(ctx);
    const { data: allowed, error: errAllowed } = await sb.from("mcp_tabelas_expostas").select("tabela").eq("tabela", tabela).maybeSingle();
    if (errAllowed) return { content: [{ type: "text", text: errAllowed.message }], isError: true };
    if (!allowed) {
      return {
        content: [
          {
            type: "text",
            text: `Tabela "${tabela}" n\xE3o est\xE1 liberada. Pe\xE7a ao administrador para adicion\xE1-la em Listas \u2192 Disponibilizar dados para Cloud Code / Cursor / ChatGPT.`
          }
        ],
        isError: true
      };
    }
    let q = sb.from(tabela).select(colunas && colunas.trim() ? colunas : "*").limit(limit ?? 50);
    if (order_by) q = q.order(order_by, { ascending: (ordem ?? "asc") === "asc" });
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tabela, registros: data ?? [], count: (data ?? []).length }
    };
  }
});

// src/lib/mcp/tools/listar-tabelas-disponiveis.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var listar_tabelas_disponiveis_default = defineTool8({
  name: "listar_tabelas_disponiveis",
  title: "Listar tabelas liberadas para consulta",
  description: "Retorna a lista de tabelas do Pilar que est\xE3o liberadas para consulta via MCP (configuradas na tela 'Disponibilizar dados para Cloud Code / Cursor / ChatGPT'). Use antes de 'consultar_tabela'.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser8(ctx);
    const { data, error } = await sb.from("mcp_tabelas_expostas").select("tabela, descricao").order("tabela");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tabelas: data ?? [], count: (data ?? []).length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ioxugupvxlcdweldocmq";
var mcp_default = defineMcp({
  name: "pilar-mcp",
  title: "Pilar CRM MCP",
  version: "0.3.0",
  instructions: "Ferramentas do Pilar CRM.\nLeitura: `whoami`, `list_segmentos`, `list_empresas` (filtros UF/cidade/segmento/e-mail/WhatsApp), `list_produtos`.\nConsulta gen\xE9rica: `listar_tabelas_disponiveis` mostra as tabelas liberadas pelo administrador, e `consultar_tabela` retorna registros de qualquer uma dessas tabelas (respeitando RLS).\nEscrita \u2014 Prospec\xE7\xE3o: `salvar_empresa_prospectada` insere UMA empresa pesquisada na web na tela 'Prospec\xE7\xE3o Via Cloud Code / Cursor ou ChatGPT'; `salvar_empresas_prospectadas` insere um lote (at\xE9 100). Use SEMPRE que o usu\xE1rio pedir para pesquisar empresas na internet e trazer os resultados para dentro do Pilar. O usu\xE1rio depois revisa e importa para o cadastro definitivo. Todas as ferramentas respeitam as permiss\xF5es (RLS) do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_empresas_default,
    list_produtos_default,
    list_segmentos_default,
    listar_tabelas_disponiveis_default,
    consultar_tabela_default,
    add_prospeccao_empresa_default,
    add_prospeccao_empresas_bulk_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
