ALTER TABLE public.cv_cameras
  ADD COLUMN IF NOT EXISTS tem_ptz BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tem_audio BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS onvif_user TEXT,
  ADD COLUMN IF NOT EXISTS onvif_pass TEXT,
  ADD COLUMN IF NOT EXISTS onvif_porta INTEGER DEFAULT 80,
  ADD COLUMN IF NOT EXISTS ptz_velocidade_padrao NUMERIC(3,2) NOT NULL DEFAULT 0.5;